### ISSUE TITLE
Add repo info in META

### ISSUE THREAD

**Issue by Tux** [JJ/perl-mp3-info#4]
Something like. Choose wisely
```
resources: 
  IRC: irc://irc.perl.org/#perl
  homepage: https://metacpan.org/pod/MP3::Info
  license: http://dev.perl.org/licenses/
  repository: https://github.com/JJ/perl-mp3-info
```
This will automatically create entries in the left pane on MetaCPAN
